version: "3.7"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - app-network

  app:
    build: 
      context: ./app
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    # ports:
      # - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:latest
    ports:
      - 5436:5432
    # environment:
    #   - POSTGRES_PASSWORD=S3cret
    #   # - POSTGRES_USER=citizix_user
    #   # - POSTGRES_DB=citizix_db
    environment:
      - POSTGRES_USER=passAPI
      - POSTGRES_PASSWORD=asdgfbqet13ARf
      - POSTGRES_DB=log
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
