version: "3.7"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      POSTGRES_USER: passAPI
      POSTGRES_PASSWORD: asdgfbqet1@$FwQW$%#43
    depends_on:
      - app
    networks:
      - app-network

  app:
    build: 
      context: ./app
      dockerfile: ./Dockerfile
    
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: passAPI
      POSTGRES_PASSWORD: asdgfbqet1
      POSTGRES_DB: log
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
