// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package log

import (
	"database/sql"
)

// Injectors from wire.go:

func Wire(db *sql.DB) *middleware {
	logRepository := ProvideRepository(db)
	logService := ProvideService(logRepository)
	logMiddleware := ProvideHandler(logService)
	return logMiddleware
}
