// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package password

// Injectors from wire.go:

func Wire() *handler {
	passwordService := ProvideService()
	passwordHandler := ProvideHandler(passwordService)
	return passwordHandler
}
